name: Set up .NET environment
runs:
    using: "composite"
    steps:
        -   name: Set up .NET Core SDK
            uses: actions/setup-dotnet@v4
            with:
                dotnet-version: '9.x'
