name: Deploy

on:
    release:
        types: [ published ]

jobs:
    test:
        uses: ./.github/workflows/test.yml
    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Set up .NET Core SDK
                uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: |
                        8.x
                        9.x
            -   name: Pack
                run: dotnet pack ./src/AustinS.TailwindCssTool -c Release /p:Version=$RELEASE_VERSION
                env:
                    RELEASE_VERSION: ${{ github.event.release.tag_name }}
            -   name: Publish to NuGet
                run: dotnet nuget push ./src/AustinS.TailwindCssTool/bin/Release/AustinS.TailwindCssTool.$RELEASE_VERSION.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_AUTH_TOKEN
                env:
                    RELEASE_VERSION: ${{ github.event.release.tag_name }}
                    NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
