name: Deploy

on:
    release:
        types: [ published ]

jobs:
    test:
        uses: ./.github/workflows/test.yml
    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   uses: ./.github/actions/setup-dotnet-environment
            #-   name: Build
            #    run: dotnet build -c Release
