name: Test

on:
    workflow_call:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
            -   uses: ./.github/actions/setup-dotnet-environment
            -   name: Build for .NET 8
                run: dotnet build ./src/AustinS.TailwindCssTool --framework net8.0 -c Release
            -   name: Build for .NET 9
                run: dotnet build ./src/AustinS.TailwindCssTool --framework net9.0 -c Release
            -   name: Build for .NET 10
                run: dotnet build ./src/AustinS.TailwindCssTool --framework net10.0 -c Release
